name: Java App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Print Maven Project Info
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          PACKAGE_PATH="target/$ARTIFACT_ID-$VERSION.jar"
          echo "::notice title=Maven Package Info::Artifact ID: $ARTIFACT_ID, Version: $VERSION, Package: $PACKAGE_PATH"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: target/*.jar

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
